server:
  port: 8081

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/


spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: marketplace-service