database:
  in-memory: false


spring:
  data:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketplace_reserve
    username: postgres
    password: password


pages:
  size: 5