server:
  port: 8889

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    enabled: true
    register-with-eureka: true

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Frostetsky/MNS.git
          searchPaths: ['/config/']
          clone-on-start: true
          default-label: master